name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: ha-ha
        id: joke
        uses: ./.github/actions/joke-action

      - name: Comment on issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              "issue_number": "${{ github.event.issue.number }}",
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.repository }}",
              "body": "Here is a joke: ${{ steps.joke.outputs.joke-output }}"
            })

      
      
      
